; PlatformIO Project Configuration File
;
; NB!!! Code #defines take presidence over -D settings (-D settings ignored if #defines in code)
;       ... remove or comment out #defines in code to allow -D settings to work
; Aug 2026 NOTES ... after rebuilding this CORE FRAMEWORK I FINALLY
;                    found out this INI file could be the source of
;                    most of the KEY Variables within the CORE using
;                    build_flags = -D<define_name>                     ; #define blah
;                                  -D<define_name>=<some_value>        ; #define blah blah        
;                                  -D<define_name>=\"<string value?\"  ; #define blah "blah"
;     FURTHER!!! ... these -Ds can be common to all env types using: extends and ${blah.<[lbl]>}                    
;
; Little File System files MUST BE MANUALLY loaded using pio run -t uploadfs
;                    this cmd wipes out the data flash and completely uploads the entire data fldr      
;  
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;default_envs = esp32dev    ; Program via USB PORT
default_envs = esp32dev-ota ; Program via OTA


; Common Settings
[_deps]
lib_deps = 
    https://github.com/bblanchon/ArduinoJson.git
    https://github.com/ESP32Async/AsyncTCP.git
    https://github.com/mathieucarbou/ESPAsyncWebServer.git
    https://github.com/thomasfredericks/Bounce2.git
    adafruit/Adafruit NeoPixel@^1.11.0
   knolleary/PubSubClient

[_hdr]
build_flags = 
   -D_DEV_ESP32
   -D_AUTHOR=\"BXDOBS\"
   -D_CORE_VER_DATE=\"2026-09-09\"
   -D_CORE_VER=\"03v2\" 
 
[_ecc]
build_flags = 
   -D_DEV_NAME=\"ESP32_CORE\"
   -D_APP_TITLE=\"Esp32_Core\"
   -D_APP_BTN=\"Esp32_App\"
   -D_APP_HTML=\"/espcore/live.html\"
   -D_APP_TOPIC=\"\"
   -D_APP_ENABLE=false
   -D_LND=18                  ; Device IP 4
   -D_LNO=18                  ; OTA    IP 4

[_app]
build_flags = 
   -D_DEV_NAME=\"Firecracker_(esp32)\"
   -D_APP_TITLE=\"X10_Firecracker_(esp32)_Interface\"
   -D_APP_VER_DATE=\"2026-09-09\"
   -D_APP_VER=\"03v1\" 
   -D_APP_BTN=\"FC_App\"
   -D_APP_HTML=\"/fc/fc_index.html\"
   -D_APP_TOPIC=\"/Firecracker/cmd\"
   -D_APP_ENABLE=true
   -D_LND=18                  ; Device IP 4
   -D_LNO=18                  ; OTA    IP 4

[_fs]
build_flags =
   -D_HAS_FS=1   
   -D_USE_FS_HTML=1

[_io]  
build_flags = 
   -D_LED_PIN=2
   -D_BOOT_BTN_PIN=0
   -D_BOOT_BTN_DB_TIME=25    ; Boot Button Debounce Time 25 mSec
   -D_BOOT_BTN_CFG_TIME=5    ; Boot Button CFG Time 2.5 Secs = 5 Tocks

[_rgb]  
build_flags = 
   -D_HAS_RGB=0               ; _HAS_RGB=1 board has RGB led _HAS_RGB=0 board has no RGB led
   -D_RGB_ENABLED=true        ; enable RGB led logic (true | false)
   -D_RGB_PIN=16
   -D_RGB_PIXELS=1

[_log]  
build_flags = 
   -D_LOG_SER=false            ; Log to Serial Montitor
   -D_LOG_MQTT=true           ; Log to MQTT 
   -D_SYS_MSG=0x00            ; System Log MSG
   -D_INFO_MSG=0x80           ; Information Log MSG
   -D_ERR_MSG=0x40            ; Error Log MSG
   -D_WRN_MSG=0x20            ; Warning Log MSG
   -D_MISC_MSG=0x10           ; Misc Log MSG
   -D_DBG1_MSG=0x08           ; Debug Level 1 Log Msg 
   -D_DBG2_MSG=0x04           ; Debug Level 2 Log Msg
   -D_DBG3_MSG=0x02           ; Debug Level 3 Log Msg
   -D_DBG4_MSG=0x01           ; Debug Level 4 Log Msg

[_net]  
build_flags = 
   -D_MK1=255                 ; Mask 1
   -D_MK2=255                 ; Mask 2
   -D_MK3=255                 ; Mask 3
   -D_MK4=0                   ; Mask 4
   -D_LN1=10                  ; IP 1
   -D_LN2=213                 ; IP 2
   -D_LN3=69                  ; IP 3
   -D_LNR=90                  ; Router IP 4
   -D_LNM=17                  ; MQTT   IP 4
   -D_MQTT_PORT=1883
   -D_AWS_PORT=80

[_tmrs]  
build_flags = 
   -D_OTA_TIMEOUT=5           ; OTA Timeout Minutes
   -D_WDT_TIMEOUT=7           ; Watchtdog Iimeout Seconds 
   -D_TEST_TIMEOUT=1          ; Test Mode Iimeout Minutes
   -D_TOCKS_PER_MIN=120       ; 120 500mS tocks = 1 Minute

[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
board_build.filesystem = littlefs
framework = arduino
upload_speed = 115200
monitor_speed = 115200
upload_port = COM7
monitor_port = COM7
lib_extra_dirs = C:/PIO/Projects

extends = _deps, _hdr, _ecc, _app, _fs, _io, _rgb, _log, _net, _tmrs

build_flags = 
   -D_USB_ENVS
   ${_hdr.build_flags}
   ${_app.build_flags}
   ${_fs.build_flags}
   ${_io.build_flags}
   ${_rgb.build_flags}
   ${_log.build_flags}
   ${_net.build_flags}
   ${_tmrs.build_flags}
 
[env:esp32dev-ota]
platform = espressif32@6.5.0
board = esp32dev
board_build.filesystem = littlefs
framework = arduino
upload_port = 10.213.69.18 ; 254 or the lnd val
upload_speed = 115200
monitor_speed = 115200
upload_protocol = espota
lib_extra_dirs = C:/PIO/Projects

upload_flags =
    --port=3232
    "--auth=ota@123@ABC"
    --timeout=30
    --debug

extends = _deps, _hdr, _ecc, _app, _fs, _io, _rgb, _log, _net, _tmrs

build_flags = 
   -D_OTA_ENVS
   ${_hdr.build_flags}
   ${_app.build_flags}
   ${_fs.build_flags}
   ${_io.build_flags}
   ${_rgb.build_flags}
   ${_log.build_flags}
   ${_net.build_flags}
   ${_tmrs.build_flags}

[env:esp32camv]
;platform = espressif32
platform = espressif32@6.5.0
board = esp-wrover-kit
framework = arduino
upload_port = COM5
monitor_port = COM5
upload_speed = 115200
monitor_speed = 115200
board_build.partitions = default_ota.csv
build_flags = -DCAM_ESP32 -D_ESPCAM
extends = common

[env:esp32camv-ota]
;platform = espressif32
platform = espressif32@6.5.0
board = esp-wrover-kit
framework = arduino
;upload_speed = 115200
upload_protocol = espota
upload_port = 10.213.69.18
upload_flags =
    --port=3232
    "--auth=ota@123@ABC"
    --timeout=30
    --debug
monitor_speed = 115200
board_build.partitions = default_ota.csv
build_flags = -DCAM_ESP32 -D_ESPCAM
extends = common

;lib_deps = 
    ;ESP Async WebServer
    ;AsyncTCP
    ;ArduinoJson
    ;Bounce2 
;   https://github.com/bblanchon/ArduinoJson.git
;   https://github.com/ESP32Async/AsyncTCP.git
;   https://github.com/mathieucarbou/ESPAsyncWebServer.git
;    https://github.com/thomasfredericks/Bounce2.git
 
[env:esp32cam]
platform = espressif32@6.5.0
board = esp32cam
framework = arduino
upload_speed = 115200
monitor_speed = 115200
upload_port = COM5
monitor_port = COM5
build_flags = -DCAM_ESP32 -D_ESPCAM

extends = common

[env:esp32cam-ota]
platform = espressif32@6.5.0
board = esp32cam
framework = arduino
upload_protocol = espota
upload_port = 10.213.69.18
upload_flags =
    --port=3232
    "--auth=ota@123@ABC"
    --timeout=30
    --debug
build_flags = -DCAM_ESP32 -DOTA_MODE -D_ESPCAM
monitor_speed = 115200
board_build.partitions = default_ota.csv
;board_build.partitions = default_8MB.csv
extends = common
